### ISSUE TITLE
Not working on related/upsell/cross-sell

### ISSUE THREAD

**Issue by jarnail1004** [magespecialist/m2-MSP_UseLowestPriceForTier#1]
It might not be issue but seem to be extra feature. This module working fine on category page and search page but not related/upsell/cross-sell products. Can you guide me how to achieve this?

**Comment by daniloargentiero** [comment]
Hi jarnail1004,
look at new relase 0.2.0

**Comment by jarnail1004** [comment]
Thanks DaniloEmpire. It fixed. and ther is minor issue and both prices are displaying now. I need to hide Regular price and its in related/upsell/cross-sell section. Can you please help me? I also added screen shot.

![git](https://user-images.githubusercontent.com/26272597/29154622-58e37ed0-7db3-11e7-896a-c4d50fd684dd.png)
